# Site settings
title: beastman.ca
author: "Brydon Eastman"
email: brydon.eastman@gmail.com
description: "Really cool blog about ... something"
#baseurl: "/" # comment out if site is in root folder
url: "http://beastman.ca"
more: "read more"

# Comments
disqus_username: "brydoneastman"
#isso_domain: "comments.mysite.org"

# Links

links:
  - github: "https://github.com/brydon/"
  - steam: "http://steamcommunity.com/id/me/"


# Build settings
markdown: redcarpet
permalink: /:title/
excerpt_separator: "<!--more-->"

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
